name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-10.15, dc: ldc-latest }
          - { os: macos-11.0, dc: ldc-latest  }
        build: [Debug, Release]

    name: "${{matrix.config.os}}:${{matrix.build}}"

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.1.1

    - name: 'Prepare'
      run: |
        brew install openssl@1.1
        brew install llvm

    - name: 'Build & Test'
      run: |
        # Build the project, with its main file included, without unittests
        export OPENSSL_ROOT_DIR="$(ls -rd -- /usr/local/Cellar/openssl@1.1/* | head -n 1)"
        dub build --compiler=$DC
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        # dub test -b unittest-cov --compiler=$DC
        # Upload code coverage
        # bash <(curl -s https://codecov.io/bash)
