name: macos

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-10.15, dc: ldc-latest }
          - { os: macos-11.0, dc: ldc-latest  }
        build: [Debug, Release]

    name: "${{matrix.config.os}}:${{matrix.build}}"

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.1.1

    - name: 'Prepare'
      run: |
        brew install openssl@1.1
        brew install llvm

    - name: 'Build'
      run: |
        # Build the project, without unittests
        dub build --compiler=$DC
