name: ubuntu

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.1.1

    - name: 'Prepare'
      run: sudo apt-get update; sudo apt-get install --fix-missing cmake gcc docker.io containerd runc

    - name: 'Build & Test'
      run: |
        # Build the project, without unittests
        dub build --compiler=$DC
        # Build and run tests
        dub test -b unittest-cov --compiler=$DC
        # Upload code coverage
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
