name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        # dc: [ldc-latest, ldc-beta, dmd-latest, dmd-master, dmd-beta]
        # arch: [x86, x86_64]
        config:
          - { os: windows-2016, vs: "Visual Studio 2017", dc: ldc-latest } # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md#visual-studio-enterprise-2017
          - { os: windows-2019, vs: "Visual Studio 2019", dc: ldc-latest } # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019
        build: [Debug, Release]
        platform: [Win32, x64]

    name: "${{matrix.config.vs}}:${{matrix.platform}}:${{matrix.build}}"

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.1.1

    - name: 'Prepare'
      run: |
        "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
        choco -y install openssl

    - name: 'Build & Test'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler=$DC
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        # dub test -b unittest-cov --compiler=$DC
        # Upload code coverage
        # bash <(curl -s https://codecov.io/bash)
